### ISSUE TITLE
Cancel payment raises CONNECT_PLATFORM_ERROR

### ISSUE THREAD

**Issue by dimasusername** [Ingenico-ePayments/connect-sdk-ruby#2]
`client.merchant(merchant_id).payments.cancel(payment_id)`

<img width="632" alt="Screen Shot 2019-10-21 at 10 24 18 AM" src="https://user-images.githubusercontent.com/7683329/67184697-f9c85d00-f3ec-11e9-88ec-60df4a4e5e3f.png">

**Comment by rikvanthof** [comment]
Do you only get this error for the cancel payment? Which version of the SDK are you using?

**Comment by rob-spoor** [comment]
@dimasusername: we noticed that the HTTP client library was adding a content type after the authentication signature was created, even though it was not needed. As a result, the signature did not match with what was expected. Version 2.14.0 was just released which should fix this issue.
